version: '3.4'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: sqlserver-compose
        environment:
            SA_PASSWORD: "Admin123"
            ACCEPT_EULA: "Y"
        networks:
            - app-network
        ports:
            - "1433:1433"
    redis:
        image: redis:latest
        container_name: redis-cache-compose
        networks:
            - app-network
        ports:
            - "6379:6379"
    student_management:
        image: ${DOCKER_REGISTRY-}studentmanagement
        build:
          context: .
          dockerfile: Student_Management/Dockerfile
        networks:
            - app-network
        ports:
            - "8080:8080"
            - "8081:8081"
networks:
    app-network: